services:
  - type: web
    name: rams-automater
    env: python
    buildCommand: |
      cd frontend && yarn install && yarn build
    startCommand: |
      cd backend && pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: JWT_SECRET
        value: change_me_securely









